#!/bin/bash

#written 6th January 2023 by AW
#the script is creating backup of all home directoryW
tar -cvf /home/ad/bash-udemy-course/section1/6_backup_script/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2>/dev/null
